### ISSUE TITLE
Each event list element displays pertinent information

### ISSUE THREAD

**Issue by graceful-frog** [make-it-so-/mgt656-spring-2015-project#11]
about the event: title, date, and how

many people are RSVPd etc. It should include the default events that come with the 

project. E.g. in the above example those details should be where you see "...".

d. Every event li element should have an HTML5 time tag that has a datetime attribute 

equal to the time in ISO 8601 format. The text of the tag should be the datetime in 

natural language, including the time. For example, it may look like

e. <time datetime="2014-11-12 09:30:0.0+07:00">

 Wednesday, Nov 12 at 9:30AM

 </time>

**Comment by envirosarah** [comment]
Already included in the default code
