### ISSUE TITLE
Form srtucture

### ISSUE THREAD

**Issue by graceful-frog** [make-it-so-/mgt656-spring-2015-project#16]
1. I must specify the following attributes of a new event: title, location, image, year, month, day,

hour, and minute.

a. There must be a form element with name={{field}} for each of these, where "{{field}}" 

is title, location, etc.

b. Every form element requires a label element with appropriate for attribute. For 

example:

c. <form method="POST">

 <label for="title">Put title here:</label>

 <input type="text" name="title" id="title">

 ... 

 </form>

d. The year, month, day, hour, and minute form elements should be select elements.

e. The minute should only have 0, and 30 as selections. (At the hour and half hour).

f. The hour select should be in 24-hour time format: 0-23 are selectable.

g. The month select should have integer value attributes and refer to months by their 

names: January, February, etc.

h. You should only be able to schedule events in 2015 and 2016

**Comment by envirosarah** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
